name: C/C++ CI

on:
  pull_request:
    branches: [ master, develop, feature/* ]

jobs:
  compile:
    name: build-and-compile
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: compile
      run: | 
        cl.exe main.cpp /std:c++latest /Fe:spark.exe
      shell: cmd
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: spark
        path: |
          spark.exe
  execute:
    name: run-on-windows-and-mac
    needs: [compile]
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - name: download-compiler
        uses: actions/download-artifact@v2
        with:
          name: spark
      - name: run-on-windows
        if: matrix.os == 'windows-latest'
        run: |
          dir 
          spark.exe test.spark
        shell: cmd
      - name: run-on-mac
        if: matrix.os == 'macos-latest'
        run: | 
          ls
          cat test.spark
          chmod 755 spark.exe
          ./spark.exe test.spark
        shell: bash
