name: C/C++ CI

on:
  pull_request:
    branches: [ master, develop, feature/* ]

jobs:
  windows:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      run: | 
        cl main.cpp /Fe:spark-windows /std:c++latest
    - name: run
      run: |
        spark-windows.exe test.spark
      shell: cmd
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: |
          spark-windows.exe
  mac:
    name: run on mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile
        run: |
          g++ -std=c++17 main.cpp -o spark-mac
      - name: run
        run: |
          ./spark-mac test.spark
        shell: bash
      - name: upload executable
        uses: actions/upload-artifact@v2
        with:
          name: mac
          path: |
            spark-mac
          
