name: C/C++ CI

on:
  pull_request:
    branches: [ master, develop, feature/* ]

jobs:
  compile:
    name: build-and-compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: | 
        g++ -std=c++17 main.cpp -o spark
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: spark
        path: |
          spark
  execute:
    name: run-on-windows-and-mac
    needs: [compile]
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: download-compiler
        uses: actions/download-artifact@v2  
        with:
          name: spark
      - name: run-on-windows
        if: matrix.os == 'windows-latest'
        run: |
          ./spark test.spark
      - name: run-on-mac
        if: matrix.os == 'macos-latest'
        run: | 
          chmod +x spark
          ./spark test.spark
        shell: bash
