name: C/C++ CI

on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master, develop, feature/* ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: windows
      if: matrix.os == 'windows-latest'
      run: | 
        spark test.txt
      shell: cmd
    - name: mac
      if: matrix.os == 'macos-latest'
      run: |
        sudo chmod +x spark.exe
        ./spark.exe test.txt
      shell: bash
